---
title: '2019-04-24'
author: "ekubo"
date: "4/24/2019"
output: html_document
---

```{r}
Vec1<-c(1:6)
Vec1

```

```{r}
Mat1
Mat1[[2]]
```
```{r}
MAT2<-matrix(c("a","b","c","d"),2,2)
MAT2
class(MAT2)
typeof(MAT2)
MAT2[[2]]
MAT2[c(T,F,F,T)]
MAT2[c(1,4)]##同上
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517), ##欄位名稱=欄位值
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50))
StuList 
```
```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517), ##欄位名稱=欄位值
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50))
StuDF 
```

```{r}
StuList[[2]][[3]]
```
```{r}
StuDF[["姓名"]][[3]]
```

```{r}
as.data.frame(StuList)->StuDF2
class(StuDF2)
```
```{r}
StuDF2
```
```{r}
as.data.frame(StuList,stringsAsFactors = F) -> StuDF3
class(StuDF3)
```
```{r}
StuDF3
```
```{r}
LETTERS
chosenLETTERS<- LETTERS[1:15]
matObj1<-matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
matObj1[11]
matObj1[1,3]
matObj1[c(1,4),c(2,3)]##同時滿足第1,4列，2,3排
matObj1[c(T,F,F,T,F),c(F,T,T)]
matObj1[c(1,4),c(F,T,T)]
```
```{r}
LETTERS
chosenLETTERS <- LETTERS[1:8]
m <- matrix(chosenLETTERS,2,4)
m
tolower(m) # 轉成小寫
m
toupper(m) # 轉成大寫
m
```
```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
class(classSurvey)
```
取出性別，學分數(data frame之角度)
```{r}
classSurvey[c(1:60),c(4,5)]
classSurvey[,4:5]
classSurvey[,c(4,5)]
classSurvey[,c(F,F,F,T,T,F)]
```
再取一次，list的角度
```{r}
classSurvey[c("性別","本學期學分數")]
```

